### ISSUE TITLE
How can I join your organization?

### ISSUE THREAD

**Issue by CooperFu** [tomorrowchuang/laipanel#19]
### tomorrowchuang Looks like so Cool!

**Comment by ceclinux** [comment]
Dear @CooperFu ：

感谢您对明创的关注，祝贺您顺利通过了简历审核，进入岗位的面试环节。面试具体安排如下：

Thank you for your interest in Tomorrowchuang. We are pleased to invite you for interview. Please confirm some details of your interview as follows.

时间 Date & time：2018-06-08 19:00

地点 Address：北京无二之旅科技公司福鱼会议室

面试官 Interviewer： 明创CTO Nicholas Xu

此致
敬礼！

Best regards,

 

                                                                              华兴资本集团China Renaissance Group

                                                                                                                   星起 Starup

                                                                                           人力资源部Human Resources

**Comment by ceclinux** [comment]
Dear @CooperFu ：

感谢您对明创的关注，祝贺您顺利通过了简历审核，进入岗位的面试环节。面试具体安排如下：

Thank you for your interest in Tomorrowchuang. We are pleased to invite you for interview. Please confirm some details of your interview as follows.

时间 Date & time：2018-06-08 19:00

地点 Address：北京无二之旅科技公司福鱼会议室

面试官 Interviewer： 明创CTO Nicholas Xu

此致
敬礼！

Best regards,
明创 tomorrowchuang
人力资源部Human Resources

**Comment by CooperFu** [comment]
Dear @ceclinux  : 

实在抱歉, 没看见这条面试信息. 19:00的时候 Nicholas Xu 还在问我关于是否上线新 Feature 的事宜. 我猜贵司 CEO 应该也忘记了 : (

But
我不想错过这次机会. 之前的种种事迹让我了解到, 贵司是个有追求/有梦想的公司. 虽然原部门支离破碎, 如今四海为家. 但是皇帝岛船上之行让付某毕生难忘.

希望贵司可以内部探讨一下. 可否更改面试时间.  斗胆建议下周一可否?

> Best regards,
> Cooper Fu
